spring:
  application:
    name: actuator-zuul
zuul:
  prefix: /hfms
  routes:
    hfms-appli: /**
server:
  port: 2999

eureka:
  client:
    service-url:
      defaultZone: http://localhost:3000/eureka/