server:
  port: 9399
spring:
  application:
    name: Monitor-Server
  freemarker:
    allow-session-override : true
    allow-request-override: true
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    request-context-attribute: request
    suffix: .ftl
    template-loader-path: classpath:/templates
logging:
  config: classpath:logback-spring.xml
log2path: D:/actuators/logs2
# email 配置
email:
  config:
    myAddress: li369436113@163.com
    passwordEmail: li123456
    monitorEmailTemplate: /pages/email/monitorEmail.ftl
#eureka:
  #client:
    #service-url:
      #defaultZone: http://localhost:3000/eureka/
